"""Agent 提示词模板"""

from app.prompts.profile_prompts import PROFILE_EXTRACTION_PROMPT, PROFILE_UPDATE_PROMPT
from app.prompts.resource_prompts import (
    DOCUMENT_GENERATION_PROMPT,
    MINDMAP_GENERATION_PROMPT,
    EXERCISE_GENERATION_PROMPT,
    CODE_GENERATION_PROMPT,
    READING_GENERATION_PROMPT,
    VIDEO_GENERATION_PROMPT,
)
from app.prompts.qa_prompts import QA_SYSTEM_PROMPT, FEYNMAN_QA_PROMPT
from app.prompts.eval_prompts import EVALUATION_PROMPT

__all__ = [
    "PROFILE_EXTRACTION_PROMPT",
    "PROFILE_UPDATE_PROMPT",
    "DOCUMENT_GENERATION_PROMPT",
    "MINDMAP_GENERATION_PROMPT",
    "EXERCISE_GENERATION_PROMPT",
    "CODE_GENERATION_PROMPT",
    "READING_GENERATION_PROMPT",
    "VIDEO_GENERATION_PROMPT",
    "QA_SYSTEM_PROMPT",
    "FEYNMAN_QA_PROMPT",
    "EVALUATION_PROMPT",
]
